# Generated by Django 2.1.5 on 2019-11-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorLoginDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.BooleanField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('bloodgroup', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lastdonationdate', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='donorlogin',
            name='age',
        ),
        migrations.RemoveField(
            model_name='donorlogin',
            name='bloodgroup',
        ),
        migrations.RemoveField(
            model_name='donorlogin',
            name='city',
        ),
        migrations.RemoveField(
            model_name='donorlogin',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='donorlogin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='donorlogin',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='donorlogin',
            name='lastdonationdate',
        ),
        migrations.RemoveField(
            model_name='donorlogin',
            name='name',
        ),
        migrations.RemoveField(
            model_name='donorlogin',
            name='state',
        ),
        migrations.RemoveField(
            model_name='donorlogin',
            name='weight',
        ),
    ]
