# Generated by Django 2.1.5 on 2019-11-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191106_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorRegDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.BooleanField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('bloodgroup', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lastdonationdate', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='DonorLoginDetails',
        ),
    ]
