# Generated by Django 2.1.5 on 2019-11-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191107_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorregdetails',
            name='bloodgroup',
            field=models.CharField(choices=[('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('o+', 'O+'), ('o-', 'O-'), ('ab+', 'AB+'), ('ab-', 'AB-')], default='a+', max_length=30),
        ),
        migrations.AlterField(
            model_name='donorregdetails',
            name='gender',
            field=models.BooleanField(choices=[('m', 'Male'), ('f', 'Female')], default='f', max_length=30),
        ),
    ]
